# Test against the latest version of this Node.js version
environment:
  NODE_OPTIONS: --max_old_space_size=8192
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "12"

matrix:
  allow_failures:
    - nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  - cd workspace/assets
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - npm install -g grunt-cli

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - grunt ci

# Don't actually build.
build: off

# Cache deps
cache:
  - workspace/assets/npm_modules -> workspace/assets/package-lock.json
