language: node_js
node_js:
  - 6
  - 8
  - 9
  - 10
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 10
notifications:
  email: false
before_install: cd workspace/assets
script:
  - grunt ci
