os:
  - linux
  - windows
language: node_js
node_js:
  - 8
  - 10
  - 12
  - 13
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 13
env:
  global:
    - NODE_OPTIONS=--max_old_space_size=8192 --optimize_for_size
notifications:
  email: false
before_install: cd workspace/assets
script:
  - grunt ci
cache:
  npm: true
  directories:
    - workspace/assets/node_modules
