os:
  - linux
  - windows
language: node_js
node_js:
  - 6
  - 8
  - 10
  - 12
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 6
    - node_js: 12
notifications:
  email: false
before_install: cd workspace/assets
script:
  - grunt ci
cache:
  npm: true
  directories:
    - workspace/assets/node_modules
